management:
  endpoints:
    web:
      exposure:
        include: health # 필요한 경우 info, metrics 등 추가
  endpoint:
    health:
      show-details: never # 외부에는 상태 코드만 응답 (보안)

server:
  port: 9000

services:
  ai:
    url: ${AI_URL}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # TODO 실제 운영에서 수정 필요

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:input_uri}
          jwk-set-uri: ${JWK_SET_URI:input_uri}
        client-id: ${CLIENT_ID:input_client_id}

jpa.auditing:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
